name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # daily at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: write
      issues: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install prerequisites
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: blurphanatic
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: true
          config_octicon: true
          config_timezone: Europe/London
          config_twemoji: true
          plugin_languages: true
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: true
          plugin_languages_limit: 8
          plugin_languages_other: true
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}

      - name: Ensure metrics directory exists
        run: mkdir -p metrics

      - name: Copy generated SVGs into metrics/
        run: |
          # Adjust filenames if your template outputs differently.
          if [ -f "github-metrics.svg" ]; then
            mv github-metrics.svg metrics/github-metrics.svg
          fi
          if [ -f "top-langs.svg" ]; then
            mv top-langs.svg metrics/top-langs.svg
          fi

      - name: Commit & push updated metrics
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📈 Update GitHub metrics [skip ci]"
          branch: main
          file_pattern: "metrics/**"
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
